export const Tokens = {
  Utils: {
    LoggerService: Symbol('LoggerService'),
    LogFormatter: Symbol('LogFormatter'),
    FileTransport: Symbol('FileTransport'),
  },
  Common: {
    Server: {
      HttpServer: Symbol('HttpServer'),
      HttpConfig: Symbol('HttpConfig'),
      RouterConfig: Symbol('RouterConfig'),
    },
    Service: {
      InitializerService: Symbol('InitializerService'),
      StoreService: Symbol('StoreService'),
      AppConfigurationService: Symbol('AppConfigurationService'),
      UrlService: Symbol('UrlService'),
      AuthService: Symbol('AuthService'),
      PaymentService: Symbol('PaymentService'),
      EmailService: Symbol('EmailService'),
      SubscriptionService: Symbol('SubscriptionService'),
      SettingsService: Symbol('SettingsService'),
      OrderService: Symbol('OrderService'),
      MercadoPagoService: Symbol('MercadoPagoService'),
      OrderReviewService: Symbol('OrderReviewService'),
      FaceVerifyService: Symbol('FaceVerifyService'),
      DeliveryService: Symbol('DeliveryService'),
      DeliveryBillingService: Symbol('DeliveryBillingService'),
      PlanService: Symbol('PlanService'),
      MotoboyService: Symbol('MotoboyService'),
      MotoboyOrderService: Symbol('MotoboyOrderService'),
      OrderEtaServiceV2: Symbol('OrderEtaServiceV2'),
      ProductService: Symbol('ProductService'),
      StoreUserService: Symbol('StoreUserService'),
    },
    Controller: {
      BaseController: Symbol('BaseController'),
      StoreController: Symbol('StoreController'),
      AuthController: Symbol('AuthController'),
      ProductController: Symbol('ProductController'),
      OrderController: Symbol('OrderController'),
      PaymentController: Symbol('PaymentController'),
      SubscriptionController: Symbol('SubscriptionController'),
      PlatformAdminController: Symbol('PlatformAdminController'),
      PlatformPublicController: Symbol('PlatformPublicController'),
      PlanController: Symbol('PlanController'),
      MotoboyController: Symbol('MotoboyController'),
      StoreUserController: Symbol('StoreUserController'),
      DeliveryController: Symbol('DeliveryController'),
      LegalController: Symbol('LegalController'),
      OrderReviewController: Symbol('OrderReviewController'),
      DeliveryBillingController: Symbol('DeliveryBillingController'),
      MotoboyKycController: Symbol('MotoboyKycController'),
    },
    DataLayer: {
      DatabaseService: Symbol('DatabaseService'),
      GenericDao: Symbol('GenericDao'),
      StoreDao: Symbol('StoreDao'),
      UserRepository: Symbol('UserRepository'),
      StoreRepository: Symbol('StoreRepository'),
      PaymentRepository: Symbol('PaymentRepository'),
      StoreUserRepository: Symbol('StoreUserRepository'),
      OrderRepository: Symbol('OrderRepository'),
      ProductRepository: Symbol('ProductRepository'),
      SubscriptionRepository: Symbol('SubscriptionRepository'),
      PlanRepository: Symbol('PlanRepository'),
      MotoboyRepository: Symbol('MotoboyRepository'),
      OrderDeliveryRepository: Symbol('OrderDeliveryRepository'),
      OrderReviewRepository: Symbol('OrderReviewRepository'),
      MotoboyStoreRepository: Symbol('MotoboyStoreRepository'),
      OrderEtaEstimateRepository: Symbol('OrderEtaEstimateRepository'),
      AccessLogRepository: Symbol('AccessLogRepository'),
      PaymentEventRepository: Symbol('PaymentEventRepository'),
      DeliveryBillingCycleRepository: Symbol('DeliveryBillingCycleRepository'),
      DeliveryBillingChargeRepository: Symbol('DeliveryBillingChargeRepository'),
      MotoboyAuditLogRepository: Symbol('MotoboyAuditLogRepository'),
      MotoboyDocumentRepository: Symbol('MotoboyDocumentRepository'),
      MotoboyStoreRequestRepository: Symbol('MotoboyStoreRequestRepository'),
      SiteSettingRepository: Symbol('SiteSettingRepository'),
      StoreLinkHitRepository: Symbol('StoreLinkHitRepository'),
      StoreSettingsRepository: Symbol('StoreSettingsRepository'),
    },
    App: Symbol('App'),
  },
};
