import '@testing-library/jest-dom';
import React from 'react';
import { vi } from 'vitest';

vi.mock('@phosphor-icons/react', () => {
  const Icon = ({ size = 16, weight: _weight, ...props }: any) =>
    React.createElement('svg', {
      ...props,
      width: size,
      height: size,
      'data-testid': 'phosphor-icon',
    });

  return {
    __esModule: true,
    ArrowLeft: Icon,
    ArrowClockwise: Icon,
    ArrowRight: Icon,
    ArrowSquareOut: Icon,
    Bicycle: Icon,
    Buildings: Icon,
    CalendarBlank: Icon,
    CaretDown: Icon,
    CaretUp: Icon,
    Check: Icon,
    CheckCircle: Icon,
    CircleNotch: Icon,
    Clock: Icon,
    ClockCounterClockwise: Icon,
    Code: Icon,
    Copy: Icon,
    CopySimple: Icon,
    CreditCard: Icon,
    Crosshair: Icon,
    DeviceMobile: Icon,
    Fingerprint: Icon,
    ForkKnife: Icon,
    Gear: Icon,
    House: Icon,
    IdentificationCard: Icon,
    ListPlus: Icon,
    LockKey: Icon,
    MagnifyingGlass: Icon,
    MapPinLine: Icon,
    MapTrifold: Icon,
    Minus: Icon,
    Mountains: Icon,
    NotePencil: Icon,
    Package: Icon,
    PaperPlaneTilt: Icon,
    Phone: Icon,
    Plus: Icon,
    Printer: Icon,
    PlugsConnected: Icon,
    QrCode: Icon,
    Receipt: Icon,
    Robot: Icon,
    SealCheck: Icon,
    ShieldCheck: Icon,
    Sparkle: Icon,
    Storefront: Icon,
    Tent: Icon,
    Ticket: Icon,
    Trash: Icon,
    Truck: Icon,
    User: Icon,
    UserCircle: Icon,
    Users: Icon,
    Wallet: Icon,
    WarningCircle: Icon,
    WhatsappLogo: Icon,
    X: Icon,
  };
});
