import type {
  TourismDestinationSeed,
  TourismHospitalitySeed,
  TourismListingSeed,
} from './destinationTourismSeeder';

export const CUNHA_TOURISM_SOURCE =
  'Curadoria publica de Cunha: mapa turistico municipal, sites oficiais dos estabelecimentos e geocoding validado';

export const CUNHA_DESTINATION_SEED: TourismDestinationSeed = {
  name: 'Cunha',
  slug: 'cunha',
  city: 'Cunha',
  state: 'SP',
  description:
    'Destino de montanha entre o Vale do Paraiba e a Serra do Mar, conhecido por ceramica, lavanda, cachoeiras, pousadas, gastronomia e a rota Cunha-Paraty.',
  heroTitle: 'Cunha para descobrir sem pressa',
  heroSubtitle: 'Pousadas, ceramica, lavanda, restaurantes e passeios proximos da sua hospedagem.',
  lat: -23.07753,
  lng: -44.9567436,
  sortOrder: 50,
};

export const CUNHA_HOSPITALITY_SEEDS: TourismHospitalitySeed[] = [
  {
    name: 'Pousada Recanto João de Barro',
    slug: 'pousada-recanto-joao-de-barro',
    type: 'POUSADA',
    address: 'Rua Gerônimo Mariano Leite',
    addressNumber: '390',
    district: 'Centro',
    zipCode: '12530000',
    websiteUrl: 'https://www.recantojoaodebarro.com.br/',
    amenities: ['Pousada', 'Centro', 'Hospedagem'],
    geo: {
      lat: -23.071446,
      lng: -44.96563,
      formattedAddress: 'Rua Gerônimo Mariano Leite 390, Centro, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://www.recantojoaodebarro.com.br/',
    sortOrder: 10,
  },
  {
    name: 'Hotel do Parque',
    slug: 'hotel-do-parque-cunha',
    type: 'HOTEL',
    address: 'Rua Luciliano Galhardo',
    addressNumber: '25',
    district: 'Centro',
    zipCode: '12530000',
    websiteUrl: 'https://hoteldoparquecunha.com.br/',
    amenities: ['Hotel', 'Centro', 'Hospedagem'],
    geo: {
      lat: -23.073789,
      lng: -44.961422,
      formattedAddress: 'Rua Luciliano Galhardo 25, Centro, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://hoteldoparquecunha.com.br/',
    sortOrder: 20,
  },
  {
    name: 'Casa Cunha Cerâmica e Hospedagem',
    slug: 'casa-cunha-ceramica-e-hospedagem',
    type: 'CASA_TEMPORADA',
    address: 'Rua José Arantes Filho',
    addressNumber: '27',
    district: 'Vila Rica',
    zipCode: '12530000',
    amenities: ['Hospedagem', 'Cerâmica', 'Centro'],
    geo: {
      lat: -23.0738313,
      lng: -44.9625243,
      formattedAddress: 'Rua José Arantes Filho 27, Vila Rica, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl:
      'https://cunha.sp.gov.br/wp-content/uploads/2019/01/Mapa-Tur%C3%ADstico-da-Est%C3%A2ncia-Clim%C3%A1tica-de-Cunha.pdf',
    sortOrder: 30,
  },
  {
    name: 'Pousada Candeias',
    slug: 'pousada-candeias',
    type: 'POUSADA',
    address: 'Estrada do Campo Alegre',
    addressNumber: 'km 1,1',
    district: 'Aparição',
    zipCode: '12530000',
    websiteUrl: 'https://www.pousadacandeias.com.br/',
    amenities: ['Pousada', 'Natureza', 'Serra'],
    geo: {
      lat: -23.20998,
      lng: -45.00956,
      formattedAddress: 'Estrada do Campo Alegre km 1,1, Aparição, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://www.pousadacandeias.com.br/',
    sortOrder: 40,
  },
];

export const CUNHA_LISTING_SEEDS: TourismListingSeed[] = [
  {
    title: 'O Lavandário',
    category: 'PASSEIO',
    address: 'Rodovia SP-171',
    addressNumber: 'km 54,7',
    district: 'Cunha',
    zipCode: '12530000',
    websiteUrl: 'https://lavandario.com.br/informacoes/',
    featured: true,
    geo: {
      lat: -23.130109,
      lng: -44.931416,
      formattedAddress: 'O Lavandário, Rodovia SP-171 km 54,7, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://lavandario.com.br/informacoes/',
    sortOrder: 10,
  },
  {
    title: 'Contemplário',
    category: 'PASSEIO',
    address: 'Rodovia Vice Prefeito Salvador Pacetti',
    addressNumber: 'km 61,5',
    district: 'Cunha',
    zipCode: '12530000',
    websiteUrl: 'https://contemplario.com.br/',
    featured: true,
    geo: {
      lat: -23.1501321,
      lng: -44.8932156,
      formattedAddress: 'Contemplário, Rodovia Vice Prefeito Salvador Pacetti km 61,5, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://contemplario.com.br/',
    sortOrder: 20,
  },
  {
    title: 'Fazenda Aracatu',
    category: 'PASSEIO',
    address: 'Rodovia Vice Prefeito Salvador Pacetti',
    addressNumber: 's/n',
    district: 'Cunha-Paraty',
    zipCode: '12530000',
    websiteUrl: 'https://fazendaaracatu.com.br/',
    featured: true,
    geo: {
      lat: -23.135847,
      lng: -44.924888,
      formattedAddress: 'Fazenda Aracatu, Rodovia Vice Prefeito Salvador Pacetti, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://fazendaaracatu.com.br/',
    sortOrder: 30,
  },
  {
    title: 'Dona Dita Restaurante',
    category: 'RESTAURANTE_VISITAR',
    address: 'Praça Cônego Siqueira',
    addressNumber: '46',
    district: 'Centro',
    zipCode: '12530000',
    featured: true,
    geo: {
      lat: -23.074593,
      lng: -44.959413,
      formattedAddress: 'Praça Cônego Siqueira 46, Centro, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl:
      'https://cunha.sp.gov.br/wp-content/uploads/2019/01/Mapa-Tur%C3%ADstico-da-Est%C3%A2ncia-Clim%C3%A1tica-de-Cunha.pdf',
    sortOrder: 40,
  },
  {
    title: 'Drão Restaurante',
    category: 'RESTAURANTE_VISITAR',
    address: 'Alameda Lavapés',
    addressNumber: '560',
    district: 'Centro',
    zipCode: '12530000',
    websiteUrl: 'https://www.draorestaurante.com.br/',
    featured: true,
    geo: {
      lat: -23.076925,
      lng: -44.963951,
      formattedAddress: 'Alameda Lavapés 560, Centro, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://www.draorestaurante.com.br/',
    sortOrder: 50,
  },
  {
    title: 'Veríssima Bistrô',
    category: 'RESTAURANTE_VISITAR',
    address: 'Rua Manoel Prudente de Toledo',
    addressNumber: '584',
    district: 'Centro',
    zipCode: '12530000',
    featured: true,
    geo: {
      lat: -23.0807444,
      lng: -44.9563375,
      formattedAddress: 'Rua Manoel Prudente de Toledo 584, Centro, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl:
      'https://cunha.sp.gov.br/wp-content/uploads/2019/01/Mapa-Tur%C3%ADstico-da-Est%C3%A2ncia-Clim%C3%A1tica-de-Cunha.pdf',
    sortOrder: 60,
  },
  {
    title: 'Cervejaria Wolkenburg',
    category: 'NOITE',
    address: 'Estrada da Pedra da Macela',
    addressNumber: 's/n',
    district: 'Cunha',
    zipCode: '12530000',
    websiteUrl: 'https://www.wolkenburg.com.br/',
    featured: true,
    geo: {
      lat: -23.1473518,
      lng: -44.8458336,
      formattedAddress: 'Cervejaria Wolkenburg, Estrada da Pedra da Macela, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://www.wolkenburg.com.br/',
    sortOrder: 70,
  },
  {
    title: 'Suenaga e Jardineiro',
    category: 'LOJA',
    address: 'Rua Doutor Paulo Jarbas da Silva',
    addressNumber: '150',
    district: 'Centro',
    zipCode: '12530000',
    websiteUrl: 'https://suenagaejardineiro.com.br/',
    geo: {
      lat: -23.0780973,
      lng: -44.9675854,
      formattedAddress: 'Rua Doutor Paulo Jarbas da Silva 150, Centro, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://suenagaejardineiro.com.br/',
    sortOrder: 80,
  },
  {
    title: 'Casa do Artesão de Cunha',
    category: 'LOJA',
    address: 'Rua José Arantes Filho',
    addressNumber: '27',
    district: 'Vila Rica',
    zipCode: '12530000',
    geo: {
      lat: -23.0738313,
      lng: -44.9625243,
      formattedAddress: 'Casa do Artesão, Rua José Arantes Filho 27, Vila Rica, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl:
      'https://cunha.sp.gov.br/wp-content/uploads/2019/01/Mapa-Tur%C3%ADstico-da-Est%C3%A2ncia-Clim%C3%A1tica-de-Cunha.pdf',
    sortOrder: 90,
  },
  {
    title: 'Cachoeira do Pimenta',
    category: 'ATRATIVO',
    address: 'Estrada Real',
    addressNumber: 's/n',
    district: 'Cunha',
    zipCode: '12530000',
    geo: {
      lat: -23.0941499,
      lng: -44.8842257,
      formattedAddress: 'Cachoeira do Pimenta, Estrada Real, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl:
      'https://cunha.sp.gov.br/wp-content/uploads/2019/01/Mapa-Tur%C3%ADstico-da-Est%C3%A2ncia-Clim%C3%A1tica-de-Cunha.pdf',
    sortOrder: 100,
  },
  {
    title: 'Pedra da Macela',
    category: 'ATRATIVO',
    address: 'Estrada da Pedra da Macela',
    addressNumber: 's/n',
    district: 'Cunha-Paraty',
    zipCode: '12530000',
    featured: true,
    geo: {
      lat: -23.1408517,
      lng: -44.8132634,
      formattedAddress: 'Pedra da Macela, Estrada da Pedra da Macela, Cunha - SP, Brasil',
    },
    sourceUrl:
      'https://cunha.sp.gov.br/wp-content/uploads/2019/01/Mapa-Tur%C3%ADstico-da-Est%C3%A2ncia-Clim%C3%A1tica-de-Cunha.pdf',
    sortOrder: 110,
  },
  {
    title: 'Parque Estadual Serra do Mar - Núcleo Cunha',
    category: 'ATRATIVO',
    address: 'Praça Midair José Teodoro',
    addressNumber: '101',
    district: 'Centro',
    zipCode: '12530000',
    websiteUrl: 'https://www.infraestruturameioambiente.sp.gov.br/parques/parque-estadual-serra-do-mar/',
    geo: {
      lat: -23.068499,
      lng: -44.960435,
      formattedAddress: 'Praça Midair José Teodoro 101, Centro, Cunha - SP, 12530-000, Brasil',
    },
    sourceUrl: 'https://www.infraestruturameioambiente.sp.gov.br/parques/parque-estadual-serra-do-mar/',
    sortOrder: 120,
  },
];
