import type {
  TourismDestinationSeed,
  TourismHospitalitySeed,
  TourismListingSeed,
} from './destinationTourismSeeder';

export const MONTEIRO_LOBATO_TOURISM_SOURCE =
  'Curadoria publica de Monteiro Lobato: prefeitura municipal, guias locais e geocoding validado';

export const MONTEIRO_LOBATO_DESTINATION_SEED: TourismDestinationSeed = {
  name: 'Monteiro Lobato',
  slug: 'monteiro-lobato',
  city: 'Monteiro Lobato',
  state: 'SP',
  description:
    'Cidade de interior no Vale do Paraíba com turismo rural, pousadas, gastronomia local, cachoeiras, cultura e rotas ligadas ao universo de Monteiro Lobato.',
  heroTitle: 'Monteiro Lobato para descansar e explorar',
  heroSubtitle: 'Pousadas, restaurantes, atrativos rurais e experiências locais perto da sua hospedagem.',
  lat: -22.9545553,
  lng: -45.8386923,
  sortOrder: 45,
};

export const MONTEIRO_LOBATO_HOSPITALITY_SEEDS: TourismHospitalitySeed[] = [
  {
    name: 'Pousada Aldeias do Paraíso',
    slug: 'pousada-aldeias-do-paraiso',
    type: 'POUSADA',
    address: 'Estrada Sebastião Motta dos Santos',
    addressNumber: '501',
    district: 'Souzas',
    zipCode: '12250970',
    phone: '(12) 3979-9067',
    websiteUrl: 'https://aldeiasdoparaiso.com.br/',
    amenities: ['Pousada', 'Natureza', 'Turismo rural'],
    geo: {
      lat: -22.8816211,
      lng: -45.8290959,
      formattedAddress: 'Estrada Sebastião Motta dos Santos 501, Souzas, Monteiro Lobato - SP, 12250-970, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=183',
    sortOrder: 10,
  },
  {
    name: 'Pousada Aconchego do Caboclo',
    slug: 'pousada-aconchego-do-caboclo',
    type: 'POUSADA',
    address: 'Rua São Sebastião',
    addressNumber: '10',
    district: 'Souzas',
    zipCode: '12250000',
    phone: '(12) 3979-9044',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=183',
    amenities: ['Pousada', 'Bairro do Souza', 'Hospedagem'],
    geo: {
      lat: -22.8944542,
      lng: -45.8393201,
      formattedAddress: 'Rua São Sebastião 10, Souzas, Monteiro Lobato - SP, 12250-000, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=183',
    sortOrder: 20,
  },
  {
    name: 'Pousada Alto do Morro',
    slug: 'pousada-alto-do-morro',
    type: 'POUSADA',
    address: 'Estrada Municipal Vereador Pedro David',
    addressNumber: '555',
    district: 'Rio do Braço',
    zipCode: '12250000',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=183',
    amenities: ['Pousada', 'Vista', 'Interior'],
    geo: {
      lat: -22.9557102,
      lng: -45.8568181,
      formattedAddress:
        'Estrada Municipal Vereador Pedro David 555, Rio do Braço, Monteiro Lobato - SP, 12250-000, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=183',
    sortOrder: 30,
  },
  {
    name: 'Pousada Capim Limão',
    slug: 'pousada-capim-limao',
    type: 'POUSADA',
    address: 'Rodovia Monteiro Lobato',
    addressNumber: 'km 129,4',
    district: 'Monteiro Lobato',
    zipCode: '12250000',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=183',
    amenities: ['Pousada', 'Natureza', 'Mantiqueira'],
    geo: {
      lat: -22.923345,
      lng: -45.8157507,
      formattedAddress: 'Rodovia Monteiro Lobato km 129,4, Monteiro Lobato - SP, 12250-000, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=183',
    sortOrder: 40,
  },
];

export const MONTEIRO_LOBATO_LISTING_SEEDS: TourismListingSeed[] = [
  {
    title: 'Pizzaria A Taberna',
    category: 'RESTAURANTE_VISITAR',
    address: 'Praça Largo Comendador Freire',
    addressNumber: '100',
    district: 'Centro',
    zipCode: '12250000',
    phone: '(12) 3979-1016',
    featured: true,
    geo: {
      lat: -22.9548451,
      lng: -45.8381162,
      formattedAddress: 'Praça Largo Comendador Freire 100, Centro, Monteiro Lobato - SP, 12250-000, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=181',
    sortOrder: 10,
  },
  {
    title: 'Tia Nastácia Restaurante',
    category: 'RESTAURANTE_VISITAR',
    address: 'Praça Largo Comendador Freire',
    addressNumber: '50',
    district: 'Centro',
    zipCode: '12250000',
    phone: '(12) 3979-1114',
    featured: true,
    geo: {
      lat: -22.9544031,
      lng: -45.8383438,
      formattedAddress: 'Praça Largo Comendador Freire 50, Centro, Monteiro Lobato - SP, 12250-000, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=181',
    sortOrder: 20,
  },
  {
    title: 'Sítio do Pica Pau Amarelo',
    category: 'PASSEIO',
    address: 'Estrada Municipal do Livro',
    addressNumber: 's/n',
    district: 'Monteiro Lobato',
    zipCode: '12250970',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/',
    featured: true,
    geo: {
      lat: -22.9893735,
      lng: -45.7948578,
      formattedAddress: 'Sítio do Pica Pau Amarelo, Estrada Municipal do Livro, Monteiro Lobato - SP, 12250-970, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=154',
    sortOrder: 30,
  },
  {
    title: 'Pedra de Om',
    category: 'ATRATIVO',
    address: 'Travessa Braga',
    addressNumber: 's/n',
    district: 'Souzas',
    zipCode: '12250970',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=154',
    geo: {
      lat: -22.8821518,
      lng: -45.8521713,
      formattedAddress: 'Pedra de Om, Travessa Braga, Souzas, Monteiro Lobato - SP, 12250-970, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=154',
    sortOrder: 40,
  },
  {
    title: 'Igreja Matriz Nossa Senhora do Bonsucesso',
    category: 'ATRATIVO',
    address: 'Praça Deputado Cunha Bueno',
    addressNumber: 's/n',
    district: 'Centro',
    zipCode: '12250000',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=154',
    geo: {
      lat: -22.955072,
      lng: -45.838542,
      formattedAddress: 'Praça Deputado Cunha Bueno, Centro, Monteiro Lobato - SP, 12250-000, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=154',
    sortOrder: 50,
  },
  {
    title: 'Cachoeira da Mata',
    category: 'ATRATIVO',
    address: 'Bairro do Souza',
    addressNumber: 's/n',
    district: 'Souzas',
    zipCode: '12250970',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=154',
    geo: {
      lat: -22.8944542,
      lng: -45.8393201,
      formattedAddress: 'Bairro do Souza, Monteiro Lobato - SP, 12250-970, Brasil',
      precision: 'city',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=154',
    sortOrder: 60,
  },
  {
    title: 'Cervejaria Dom Quixote',
    category: 'NOITE',
    address: 'Centro',
    addressNumber: 's/n',
    district: 'Centro',
    zipCode: '12250000',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=181',
    geo: {
      lat: -22.9553542,
      lng: -45.8387146,
      formattedAddress: 'Centro, Monteiro Lobato - SP, 12250-000, Brasil',
      precision: 'city',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=181',
    sortOrder: 70,
  },
  {
    title: 'Casa do Artesão',
    category: 'LOJA',
    address: 'Rua Cônego Antônio Manzi',
    addressNumber: '110',
    district: 'Centro',
    zipCode: '12250000',
    websiteUrl: 'https://www.monteirolobato.sp.gov.br/',
    geo: {
      lat: -22.9564842,
      lng: -45.8391208,
      formattedAddress: 'Rua Cônego Antônio Manzi 110, Centro, Monteiro Lobato - SP, 12250-000, Brasil',
    },
    sourceUrl: 'https://www.monteirolobato.sp.gov.br/paginas/portal/conteudo?conteudo=181',
    sortOrder: 80,
  },
];
