import type {
  TourismDestinationSeed,
  TourismHospitalitySeed,
  TourismListingSeed,
} from './destinationTourismSeeder';

const instagram = (handle: string) => `https://www.instagram.com/${handle.replace(/^@/, '')}`;

export const SANTO_ANTONIO_PINHAL_TOURISM_SOURCE =
  'Curadoria publica de Santo Antonio do Pinhal: portal oficial de turismo, guias locais e geocoding validado';

export const SANTO_ANTONIO_PINHAL_DESTINATION_SEED: TourismDestinationSeed = {
  name: 'Santo Antônio do Pinhal',
  slug: 'santo-antonio-do-pinhal',
  city: 'Santo Antônio do Pinhal',
  state: 'SP',
  description:
    'Destino de montanha na Serra da Mantiqueira com pousadas, chalés, restaurantes, cafés, cervejaria, jardins, mirantes e passeios ao ar livre.',
  heroTitle: 'Santo Antônio do Pinhal sem perder tempo',
  heroSubtitle: 'Hospedagens, restaurantes, delivery local, cafés e passeios perto do seu chalé.',
  lat: -22.8250504,
  lng: -45.6674063,
  sortOrder: 25,
};

export const SANTO_ANTONIO_PINHAL_HOSPITALITY_SEEDS: TourismHospitalitySeed[] = [
  {
    name: 'Pousada do Cedro',
    slug: 'pousada-do-cedro',
    type: 'POUSADA',
    address: 'Estrada do Pico Agudo',
    addressNumber: 'km 5',
    district: 'Sertãozinho',
    zipCode: '12450000',
    whatsapp: '(11) 97545-4148',
    websiteUrl: 'https://www.pousadadocedro.com.br/',
    amenities: ['Pousada', 'Montanha', 'Vista'],
    geo: {
      lat: -22.846324,
      lng: -45.669866,
      formattedAddress: 'Estrada do Pico Agudo km 5, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/pousada-do-cedro',
    sortOrder: 10,
  },
  {
    name: 'Pousada Alpes',
    slug: 'pousada-alpes',
    type: 'POUSADA',
    address: 'Rua Antônio Claro',
    addressNumber: '319',
    district: 'Centro',
    zipCode: '12450000',
    whatsapp: '(12) 99745-6694',
    websiteUrl: 'https://www.pousadaalpes.com.br/',
    amenities: ['Pousada', 'Centro', 'Montanha'],
    geo: {
      lat: -22.8083294,
      lng: -45.654649,
      formattedAddress: 'Rua Antônio Claro 319, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/pousada-alpes',
    sortOrder: 20,
  },
  {
    name: 'Pousada Quatro Estações',
    slug: 'pousada-quatro-estacoes',
    type: 'POUSADA',
    address: 'Estrada Vereador Arlindo Inácio Fernandes',
    addressNumber: '2389',
    district: 'Caçununga',
    zipCode: '12450000',
    whatsapp: '(12) 99198-0944',
    websiteUrl: 'https://pousada4estacoes.com.br/',
    amenities: ['Pousada', 'Bistrô', 'Natureza'],
    geo: {
      lat: -22.804385,
      lng: -45.70528,
      formattedAddress:
        'Estrada Vereador Arlindo Inácio Fernandes 2389, Caçununga, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/pousada-quatro-estacoes-e-bistro-beneditu',
    sortOrder: 30,
  },
  {
    name: 'Vinhas do Pinhal',
    slug: 'vinhas-do-pinhal',
    type: 'POUSADA',
    address: 'Estrada Santa Cruz',
    addressNumber: '560',
    district: 'Santa Cruz',
    zipCode: '12450000',
    phone: '(12) 3666-1111',
    amenities: ['Pousada', 'Restaurante', 'Vista'],
    geo: {
      lat: -22.8109279,
      lng: -45.6781698,
      formattedAddress: 'Estrada Santa Cruz 560, Santa Cruz, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/pousada-e-restaurante-vinhas-do-pinhal',
    sortOrder: 40,
  },
  {
    name: 'Jardim Suspenso da Babilônia',
    slug: 'jardim-suspenso-da-babilonia',
    type: 'POUSADA',
    address: 'Rodovia Oswaldo Barbosa Guisardi',
    addressNumber: '5500',
    district: 'Rio Preto',
    zipCode: '12450000',
    websiteUrl: 'https://www.jardimsuspensodababilonia.com.br/',
    amenities: ['Pousada', 'Natureza', 'Vista'],
    geo: {
      lat: -22.8318548,
      lng: -45.7067293,
      formattedAddress:
        'Rodovia Oswaldo Barbosa Guisardi 5500, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/jardim-suspenso-da-babilonia',
    sortOrder: 50,
  },
];

export const SANTO_ANTONIO_PINHAL_LISTING_SEEDS: TourismListingSeed[] = [
  {
    title: 'Donna Pinha Restaurante',
    category: 'RESTAURANTE_VISITAR',
    address: 'Avenida Antônio José de Oliveira',
    addressNumber: '647',
    district: 'Centro',
    zipCode: '12450000',
    whatsapp: '(12) 99771-2885',
    websiteUrl: 'https://www.donnapinha.com.br/',
    featured: true,
    geo: {
      lat: -22.828253,
      lng: -45.664782,
      formattedAddress: 'Avenida Antônio José de Oliveira 647, Centro, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/donna-pinha',
    sortOrder: 10,
  },
  {
    title: 'La Taverna di Luca',
    category: 'RESTAURANTE_VISITAR',
    address: 'Rua Sebastião Marcondes da Silva',
    addressNumber: '28',
    district: 'Centro',
    zipCode: '12450000',
    websiteUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/la-taverna-di-luca',
    featured: true,
    geo: {
      lat: -22.824628,
      lng: -45.6669558,
      formattedAddress: 'Rua Sebastião Marcondes da Silva 28, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/la-taverna-di-luca',
    sortOrder: 20,
  },
  {
    title: 'Fornalha Pizzaria Delivery',
    category: 'RESTAURANTE_VISITAR',
    address: 'Avenida Antônio Joaquim de Oliveira',
    addressNumber: '203',
    district: 'Centro',
    zipCode: '12450000',
    whatsapp: '(12) 99648-3136',
    websiteUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/fornalha-pizzaria-delivery',
    featured: true,
    geo: {
      lat: -22.8262177,
      lng: -45.6594317,
      formattedAddress:
        'Avenida Antônio Joaquim de Oliveira 203, Centro, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/fornalha-pizzaria-delivery',
    sortOrder: 30,
  },
  {
    title: 'Cervejaria Araukarien',
    category: 'NOITE',
    address: 'Rodovia Oswaldo Barbosa Guisardi',
    addressNumber: '7600',
    district: 'Rio Preto de Baixo',
    zipCode: '12450000',
    websiteUrl: 'https://araukarien.com.br/',
    featured: true,
    geo: {
      lat: -22.8234894,
      lng: -45.7279422,
      formattedAddress:
        'Rodovia Oswaldo Barbosa Guisardi 7600, Rio Preto de Baixo, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/cervejaria-araukarien',
    sortOrder: 40,
  },
  {
    title: 'Restaurante Arco Íris',
    category: 'RESTAURANTE_VISITAR',
    address: 'Rodovia Oswaldo Barbosa Guisardi',
    addressNumber: '3363',
    district: 'Santo Antônio do Pinhal',
    zipCode: '12450000',
    websiteUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/restaurante-arco-iris',
    geo: {
      lat: -22.8292196,
      lng: -45.6419512,
      formattedAddress: 'Rodovia Oswaldo Barbosa Guisardi 3363, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/restaurante-arco-iris',
    sortOrder: 50,
  },
  {
    title: 'Jardim dos Pinhais Ecco Parque',
    category: 'PASSEIO',
    address: 'Rodovia Oswaldo Barbosa Guisardi',
    addressNumber: 's/n',
    district: 'Santo Antônio do Pinhal',
    zipCode: '12450000',
    websiteUrl: 'https://www.jardimdospinhais.com.br/',
    featured: true,
    geo: {
      lat: -22.8290697,
      lng: -45.6445704,
      formattedAddress: 'Jardim dos Pinhais Ecco Parque, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/jardim-dos-pinhais-ecco-parque',
    sortOrder: 60,
  },
  {
    title: 'Pico Agudo',
    category: 'ATRATIVO',
    address: 'Estrada para o Pico Agudo',
    addressNumber: 's/n',
    district: 'Santo Antônio do Pinhal',
    zipCode: '12450000',
    websiteUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/pico-agudo',
    featured: true,
    geo: {
      lat: -22.8634713,
      lng: -45.6513135,
      formattedAddress: 'Pico Agudo, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/pico-agudo',
    sortOrder: 70,
  },
  {
    title: 'Cachoeira do Lageado',
    category: 'ATRATIVO',
    address: 'Estrada Pedro Joaquim Lopes',
    addressNumber: '429',
    district: 'Lageado',
    zipCode: '12450000',
    websiteUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/cachoeira-do-lageado',
    geo: {
      lat: -22.7908604,
      lng: -45.6605676,
      formattedAddress: 'Cachoeira do Lageado, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/cachoeira-do-lageado',
    sortOrder: 80,
  },
  {
    title: 'Estação Eugênio Lefèvre',
    category: 'ATRATIVO',
    address: 'Rodovia Oswaldo Barbosa Guisardi',
    addressNumber: 's/n',
    district: 'Eugênio Lefèvre',
    zipCode: '12450000',
    websiteUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/estacao-eugenio-lefevre',
    geo: {
      lat: -22.8257924,
      lng: -45.6285266,
      formattedAddress: 'Estação Eugênio Lefèvre, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/estacao-eugenio-lefevre',
    sortOrder: 90,
  },
  {
    title: 'Mirante do Cruzeiro',
    category: 'ATRATIVO',
    address: 'Rua Cônego Tomaz',
    addressNumber: 's/n',
    district: 'Centro',
    zipCode: '12450000',
    websiteUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/mirante-do-cruzeiro',
    geo: {
      lat: -22.8259334,
      lng: -45.6633716,
      formattedAddress: 'Mirante do Cruzeiro, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/mirante-do-cruzeiro',
    sortOrder: 100,
  },
  {
    title: 'Artesanato João de Barro',
    category: 'LOJA',
    address: 'Avenida Antônio Joaquim de Oliveira',
    addressNumber: '500',
    district: 'Centro',
    zipCode: '12450000',
    instagramUrl: instagram('@artesanatojoaodebarro'),
    geo: {
      lat: -22.8262177,
      lng: -45.6594317,
      formattedAddress: 'Avenida Antônio Joaquim de Oliveira, Centro, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/categoria/artesanato',
    sortOrder: 110,
  },
  {
    title: 'Toca Café',
    category: 'RESTAURANTE_VISITAR',
    address: 'Rua Governador Carvalho Pinto',
    addressNumber: '600',
    district: 'Centro',
    zipCode: '12450000',
    instagramUrl: instagram('@tocacafe.sap'),
    geo: {
      lat: -22.824196,
      lng: -45.666352,
      formattedAddress: 'Rua Governador Carvalho Pinto, Centro, Santo Antônio do Pinhal - SP, 12450-000, Brasil',
    },
    sourceUrl: 'https://www.santoantoniodopinhal.tur.br/atrativos/toca-cafe',
    sortOrder: 120,
  },
];
