import type {
  TourismDestinationSeed,
  TourismHospitalitySeed,
  TourismListingSeed,
} from './destinationTourismSeeder';

export type StrategicTourismDestinationSeed = {
  source: string;
  destination: TourismDestinationSeed;
  hospitality: TourismHospitalitySeed[];
  listings: TourismListingSeed[];
};

export const STRATEGIC_TOURISM_BATCH_SOURCE =
  'Curadoria publica inicial: destinos estrategicos de serra, turismo rural, gastronomia e hospedagem regional';

export const STRATEGIC_TOURISM_DESTINATION_SEEDS: StrategicTourismDestinationSeed[] = [
  {
    source: 'Campos do Jordao: sites oficiais dos estabelecimentos, Parque Capivari, Amantikir e geocoding validado',
    destination: {
      name: 'Campos do Jordão',
      slug: 'campos-do-jordao',
      city: 'Campos do Jordão',
      state: 'SP',
      description:
        'Destino de montanha da Serra da Mantiqueira com hotelaria, gastronomia, parques, cervejaria, compras e experiências de inverno.',
      heroTitle: 'Campos do Jordão para curtir a serra',
      heroSubtitle: 'Hospedagens, restaurantes, parques e passeios perto do seu roteiro.',
      lat: -22.738589,
      lng: -45.592651,
      sortOrder: 55,
    },
    hospitality: [
      {
        name: 'Hotel Toriba',
        slug: 'hotel-toriba',
        type: 'HOTEL',
        address: 'Avenida Ernesto Diederichsen',
        addressNumber: '2962',
        district: 'Campos do Jordão',
        zipCode: '12460000',
        websiteUrl: 'https://www.toriba.com.br/',
        amenities: ['Hotel', 'Montanha', 'Gastronomia'],
        geo: {
          lat: -22.7179133,
          lng: -45.5708328,
          formattedAddress: 'Hotel Toriba, Campos do Jordão - SP, 12460-000, Brasil',
        },
        sourceUrl: 'https://www.toriba.com.br/',
        sortOrder: 10,
      },
      {
        name: 'Pousada Luis XV',
        slug: 'pousada-luis-xv',
        type: 'POUSADA',
        address: 'Rua Djalma Forjaz',
        addressNumber: '263',
        district: 'Capivari',
        zipCode: '12460000',
        websiteUrl: 'https://www.pousadaluisxv.com.br/',
        amenities: ['Pousada', 'Capivari', 'Hospedagem'],
        geo: {
          lat: -22.7188544,
          lng: -45.5671924,
          formattedAddress: 'Capivari, Campos do Jordão - SP, 12460-438, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.pousadaluisxv.com.br/',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Baden Baden',
        category: 'NOITE',
        address: 'Boulevard Genève',
        addressNumber: 's/n',
        district: 'Capivari',
        zipCode: '12460438',
        websiteUrl: 'https://www.badenbaden.com.br/',
        featured: true,
        geo: {
          lat: -22.7188544,
          lng: -45.5671924,
          formattedAddress: 'Baden Baden, Boulevard Genève, Capivari, Campos do Jordão - SP, 12460-438, Brasil',
        },
        sourceUrl: 'https://www.badenbaden.com.br/',
        sortOrder: 10,
      },
      {
        title: 'Parque Capivari',
        category: 'PASSEIO',
        address: 'Avenida José de Oliveira Damas',
        addressNumber: 's/n',
        district: 'Capivari',
        zipCode: '12460438',
        websiteUrl: 'https://www.parquecapivari.com.br/',
        featured: true,
        geo: {
          lat: -22.7153436,
          lng: -45.5657519,
          formattedAddress: 'Parque Capivari, Capivari, Campos do Jordão - SP, 12460-438, Brasil',
        },
        sourceUrl: 'https://www.parquecapivari.com.br/',
        sortOrder: 20,
      },
      {
        title: 'Morro do Elefante',
        category: 'ATRATIVO',
        address: 'Morro do Elefante',
        addressNumber: 's/n',
        district: 'Capivari',
        zipCode: '12460438',
        featured: true,
        geo: {
          lat: -22.7133037,
          lng: -45.566185,
          formattedAddress: 'Morro do Elefante, Campos do Jordão - SP, 12460-438, Brasil',
        },
        sourceUrl: 'https://www.parquecapivari.com.br/',
        sortOrder: 30,
      },
      {
        title: 'Amantikir',
        category: 'PASSEIO',
        address: 'Rodovia Campos do Jordão - Eugênio Lefèvre',
        addressNumber: 's/n',
        district: 'Gavião Gonzaga',
        zipCode: '12472800',
        websiteUrl: 'https://amantikir.com.br/',
        featured: true,
        geo: {
          lat: -22.7837241,
          lng: -45.6076094,
          formattedAddress: 'Parque Amantikir, Campos do Jordão - SP, 12472-800, Brasil',
        },
        sourceUrl: 'https://amantikir.com.br/',
        sortOrder: 40,
      },
      {
        title: 'Ducha de Prata',
        category: 'ATRATIVO',
        address: 'Avenida Roberto Simonsen',
        addressNumber: 's/n',
        district: 'Alto Capivari',
        zipCode: '12460000',
        geo: {
          lat: -22.7379544,
          lng: -45.5694055,
          formattedAddress: 'Ducha de Prata, Alto Capivari, Campos do Jordão - SP, Brasil',
        },
        sourceUrl: 'https://www.camposdojordao.sp.gov.br/',
        sortOrder: 50,
      },
      {
        title: 'Parque Estadual Campos do Jordão',
        category: 'ATRATIVO',
        address: 'Avenida Pedro Paulo',
        addressNumber: 's/n',
        district: 'Horto Florestal',
        zipCode: '12460000',
        websiteUrl: 'https://guiadeareasprotegidas.sp.gov.br/ap/campos-do-jordao/',
        geo: {
          lat: -22.6899496,
          lng: -45.4895823,
          formattedAddress: 'Parque Estadual Campos do Jordão, Avenida Pedro Paulo, Campos do Jordão - SP, Brasil',
        },
        sourceUrl: 'https://guiadeareasprotegidas.sp.gov.br/ap/campos-do-jordao/',
        sortOrder: 60,
      },
    ],
  },
  {
    source: 'Sao Luiz do Paraitinga: prefeitura municipal, atrativos historicos, Nucleo Santa Virginia e geocoding validado',
    destination: {
      name: 'São Luiz do Paraitinga',
      slug: 'sao-luiz-do-paraitinga',
      city: 'São Luiz do Paraitinga',
      state: 'SP',
      description:
        'Cidade histórica do Vale do Paraíba com centro tombado, cultura popular, festas tradicionais, mercado municipal, cachoeiras e ecoturismo.',
      heroTitle: 'São Luiz do Paraitinga com história e natureza',
      heroSubtitle: 'Hospedagens, centro histórico, cachoeiras e experiências locais em um roteiro só.',
      lat: -23.2220531,
      lng: -45.3108444,
      sortOrder: 60,
    },
    hospitality: [
      {
        name: 'Pousada Villa Parahytinga',
        slug: 'pousada-villa-parahytinga',
        type: 'POUSADA',
        address: 'Rua do Cigano',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '12140000',
        websiteUrl: 'https://www.villaparahytinga.com.br/',
        amenities: ['Pousada', 'Centro histórico', 'Hospedagem'],
        geo: {
          lat: -23.2212611,
          lng: -45.3086924,
          formattedAddress: 'Pousada Villa Parahytinga, Rua do Cigano, São Luiz do Paraitinga - SP, 12140-000, Brasil',
        },
        sourceUrl: 'https://www.villaparahytinga.com.br/',
        sortOrder: 10,
      },
      {
        name: 'Pousada Araucária',
        slug: 'pousada-araucaria-sao-luiz',
        type: 'POUSADA',
        address: 'São Luiz do Paraitinga',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '12140000',
        amenities: ['Pousada', 'Hospedagem', 'Centro'],
        geo: {
          lat: -23.2220531,
          lng: -45.3108444,
          formattedAddress: 'São Luiz do Paraitinga - SP, 12140-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.saoluizdoparaitinga.sp.gov.br/',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Igreja Matriz São Luís de Tolosa',
        category: 'ATRATIVO',
        address: 'Praça Doutor Oswaldo Cruz',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '12140000',
        featured: true,
        geo: {
          lat: -23.2222915,
          lng: -45.31022,
          formattedAddress: 'Igreja Matriz São Luís de Tolosa, São Luiz do Paraitinga - SP, 12140-000, Brasil',
        },
        sourceUrl: 'https://www.saoluizdoparaitinga.sp.gov.br/',
        sortOrder: 10,
      },
      {
        title: 'Mercado Municipal de São Luiz do Paraitinga',
        category: 'LOJA',
        address: 'Rua Coronel Manoel Bento',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '12140000',
        geo: {
          lat: -23.224515,
          lng: -45.3107889,
          formattedAddress: 'Mercado Municipal, Rua Coronel Manoel Bento, São Luiz do Paraitinga - SP, 12140-000, Brasil',
        },
        sourceUrl: 'https://www.saoluizdoparaitinga.sp.gov.br/',
        sortOrder: 20,
      },
      {
        title: 'Praça Doutor Oswaldo Cruz',
        category: 'ATRATIVO',
        address: 'Praça Doutor Oswaldo Cruz',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '12140000',
        geo: {
          lat: -23.222247,
          lng: -45.3110063,
          formattedAddress: 'Praça Doutor Oswaldo Cruz, São Luiz do Paraitinga - SP, 12140-000, Brasil',
        },
        sourceUrl: 'https://www.saoluizdoparaitinga.sp.gov.br/',
        sortOrder: 30,
      },
      {
        title: 'Cachoeira Grande',
        category: 'ATRATIVO',
        address: 'Cachoeira Grande',
        addressNumber: 's/n',
        district: 'São Luiz do Paraitinga',
        zipCode: '12140000',
        featured: true,
        geo: {
          lat: -23.122228,
          lng: -45.210167,
          formattedAddress: 'Cachoeira Grande, São Luiz do Paraitinga - SP, 12130-000, Brasil',
        },
        sourceUrl: 'https://www.saoluizdoparaitinga.sp.gov.br/',
        sortOrder: 40,
      },
      {
        title: 'Núcleo Santa Virgínia',
        category: 'PASSEIO',
        address: 'Estrada Serra do Mar',
        addressNumber: 's/n',
        district: 'Santa Virgínia',
        zipCode: '12140000',
        websiteUrl: 'https://guiadeareasprotegidas.sp.gov.br/ap/serra-do-mar-nucleo-santa-virginia/',
        geo: {
          lat: -23.3513257,
          lng: -45.1332874,
          formattedAddress: 'Núcleo Santa Virgínia, Estrada Serra do Mar, São Luiz do Paraitinga - SP, Brasil',
        },
        sourceUrl: 'https://guiadeareasprotegidas.sp.gov.br/ap/serra-do-mar-nucleo-santa-virginia/',
        sortOrder: 50,
      },
    ],
  },
  {
    source: 'Paraty: centro historico, pousadas oficiais, restaurantes e geocoding validado',
    destination: {
      name: 'Paraty',
      slug: 'paraty',
      city: 'Paraty',
      state: 'RJ',
      description:
        'Destino histórico e litorâneo da Costa Verde com centro colonial, pousadas, restaurantes, cais, praias, passeios de barco e cultura.',
      heroTitle: 'Paraty entre história, mar e gastronomia',
      heroSubtitle: 'Hospedagens, restaurantes, centro histórico e passeios para montar sua experiência.',
      lat: -23.2196461,
      lng: -44.7154196,
      sortOrder: 65,
    },
    hospitality: [
      {
        name: 'Casa Turquesa',
        slug: 'casa-turquesa',
        type: 'POUSADA',
        address: 'Rua Dona Geralda',
        addressNumber: '79',
        district: 'Centro Histórico',
        zipCode: '23970000',
        websiteUrl: 'https://casaturquesa.com.br/',
        amenities: ['Pousada', 'Centro histórico', 'Charme'],
        geo: {
          lat: -23.2202456,
          lng: -44.7126748,
          formattedAddress: 'Casa Turquesa, Rua Dona Geralda 79, Centro Histórico, Paraty - RJ, 23970-000, Brasil',
        },
        sourceUrl: 'https://casaturquesa.com.br/',
        sortOrder: 10,
      },
      {
        name: 'Pousada Literária',
        slug: 'pousada-literaria',
        type: 'POUSADA',
        address: 'Centro Histórico',
        addressNumber: 's/n',
        district: 'Centro Histórico',
        zipCode: '23970000',
        websiteUrl: 'https://www.pousadaliteraria.com.br/',
        amenities: ['Pousada', 'Centro histórico', 'Cultura'],
        geo: {
          lat: -23.2239543,
          lng: -44.713738,
          formattedAddress: 'Centro Histórico, Paraty - RJ, 23970-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.pousadaliteraria.com.br/',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Centro Histórico de Paraty',
        category: 'ATRATIVO',
        address: 'Centro Histórico',
        addressNumber: 's/n',
        district: 'Centro Histórico',
        zipCode: '23970000',
        featured: true,
        geo: {
          lat: -23.2196461,
          lng: -44.7154196,
          formattedAddress: 'Centro Histórico, Paraty - RJ, 23970-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://paraty.rj.gov.br/',
        sortOrder: 10,
      },
      {
        title: 'Banana da Terra',
        category: 'RESTAURANTE_VISITAR',
        address: 'Rua Doutor Samuel Costa',
        addressNumber: 's/n',
        district: 'Centro Histórico',
        zipCode: '23970000',
        websiteUrl: 'https://bananadaterra.com.br/',
        featured: true,
        geo: {
          lat: -23.2187082,
          lng: -44.7131598,
          formattedAddress: 'Banana da Terra, Rua Doutor Samuel Costa, Centro Histórico, Paraty - RJ, 23970-000, Brasil',
        },
        sourceUrl: 'https://bananadaterra.com.br/',
        sortOrder: 20,
      },
      {
        title: 'Quintal das Letras',
        category: 'RESTAURANTE_VISITAR',
        address: 'Rua do Comércio',
        addressNumber: 's/n',
        district: 'Centro Histórico',
        zipCode: '23970000',
        websiteUrl: 'https://www.pousadaliteraria.com.br/gastronomia/',
        geo: {
          lat: -23.2202263,
          lng: -44.7143063,
          formattedAddress: 'Quintal das Letras, Rua do Comércio, Centro Histórico, Paraty - RJ, 23970-000, Brasil',
        },
        sourceUrl: 'https://www.pousadaliteraria.com.br/gastronomia/',
        sortOrder: 30,
      },
      {
        title: 'Forte Defensor Perpétuo',
        category: 'ATRATIVO',
        address: 'Trilha do Forte',
        addressNumber: 's/n',
        district: 'Pontal',
        zipCode: '23970000',
        geo: {
          lat: -23.2117976,
          lng: -44.7114509,
          formattedAddress: 'Forte Defensor Perpétuo, Trilha do Forte, Pontal, Paraty - RJ, 23970-000, Brasil',
        },
        sourceUrl: 'https://paraty.rj.gov.br/',
        sortOrder: 40,
      },
      {
        title: 'Cais de Paraty',
        category: 'PASSEIO',
        address: 'Cais de Paraty',
        addressNumber: 's/n',
        district: 'Centro Histórico',
        zipCode: '23970000',
        featured: true,
        geo: {
          lat: -23.2196461,
          lng: -44.7154196,
          formattedAddress: 'Cais de Paraty, Paraty - RJ, 23970-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://paraty.rj.gov.br/',
        sortOrder: 50,
      },
    ],
  },
  {
    source: 'Joanopolis: atrativos naturais, Cachoeira dos Pretos, hospedagens publicas e geocoding validado',
    destination: {
      name: 'Joanópolis',
      slug: 'joanopolis',
      city: 'Joanópolis',
      state: 'SP',
      description:
        'Destino de natureza na Mantiqueira paulista com cachoeiras, pousadas, turismo rural, aventura e o circuito da Cachoeira dos Pretos.',
      heroTitle: 'Joanópolis para respirar natureza',
      heroSubtitle: 'Hospedagens, cachoeiras, restaurantes e passeios próximos da serra.',
      lat: -22.930004,
      lng: -46.275208,
      sortOrder: 70,
    },
    hospitality: [
      {
        name: 'Pousada San Lorenzo',
        slug: 'pousada-san-lorenzo',
        type: 'POUSADA',
        address: 'Joanópolis',
        addressNumber: 's/n',
        district: 'Joanópolis',
        zipCode: '12980000',
        websiteUrl: 'https://www.pousadasanlorenzo.com.br/contato',
        amenities: ['Pousada', 'Natureza', 'Hospedagem'],
        geo: {
          lat: -22.930004,
          lng: -46.275208,
          formattedAddress: 'Joanópolis - SP, 12980-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.pousadasanlorenzo.com.br/contato',
        sortOrder: 10,
      },
      {
        name: 'Pousada Solar dos Sonhos',
        slug: 'pousada-solar-dos-sonhos',
        type: 'POUSADA',
        address: 'Estrada dos Bandeirantes',
        addressNumber: 's/n',
        district: 'Da Lagoa',
        zipCode: '12980000',
        amenities: ['Pousada', 'Natureza', 'Hospedagem'],
        geo: {
          lat: -22.930004,
          lng: -46.275208,
          formattedAddress: 'Estrada dos Bandeirantes, Joanópolis - SP, 12980-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://cnpj.biz/53293699000191',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Cachoeira dos Pretos',
        category: 'ATRATIVO',
        address: 'Cachoeira dos Pretos',
        addressNumber: 's/n',
        district: 'Joanópolis',
        zipCode: '12980000',
        featured: true,
        geo: {
          lat: -22.968184,
          lng: -46.1695631,
          formattedAddress: 'Cachoeira dos Pretos, Joanópolis - SP, Brasil',
        },
        sourceUrl: 'https://www.joanopolis.sp.gov.br/',
        sortOrder: 10,
      },
      {
        title: 'Pedra do Carmo',
        category: 'ATRATIVO',
        address: 'Pedra do Carmo',
        addressNumber: 's/n',
        district: 'Joanópolis',
        zipCode: '12980000',
        geo: {
          lat: -22.9786665,
          lng: -46.1669316,
          formattedAddress: 'Pedra do Carmo, Joanópolis - SP, Brasil',
        },
        sourceUrl: 'https://www.joanopolis.sp.gov.br/',
        sortOrder: 20,
      },
      {
        title: 'Igreja Matriz de São João Batista',
        category: 'ATRATIVO',
        address: 'Rua Expedicionários Paulista',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '12980000',
        geo: {
          lat: -22.930295,
          lng: -46.274867,
          formattedAddress: 'Igreja Matriz de São João Batista, Joanópolis - SP, 12980-000, Brasil',
        },
        sourceUrl: 'https://www.joanopolis.sp.gov.br/',
        sortOrder: 30,
      },
      {
        title: 'Empório Cachoeira',
        category: 'LOJA',
        address: 'Bairro Cachoeira',
        addressNumber: 's/n',
        district: 'Cachoeira',
        zipCode: '12980000',
        geo: {
          lat: -22.974937,
          lng: -46.1376542,
          formattedAddress: 'Bairro Cachoeira, Joanópolis - SP, Brasil',
        },
        sourceUrl: 'https://www.joanopolis.sp.gov.br/',
        sortOrder: 40,
      },
    ],
  },
  {
    source: 'Extrema: ExtremaTur, hospedagens oficiais, atrativos naturais e geocoding validado',
    destination: {
      name: 'Extrema',
      slug: 'extrema',
      city: 'Extrema',
      state: 'MG',
      description:
        'Destino no sul de Minas com serra, parques, cachoeiras, turismo de aventura, hotelaria e gastronomia próxima de São Paulo.',
      heroTitle: 'Extrema para aventura e descanso',
      heroSubtitle: 'Hotéis, parques, cachoeiras, mirantes e restaurantes em uma experiência prática.',
      lat: -22.8548355,
      lng: -46.3184553,
      sortOrder: 75,
    },
    hospitality: [
      {
        name: 'Hotel Villa Lobos',
        slug: 'hotel-villa-lobos',
        type: 'HOTEL',
        address: 'Avenida Delegado Waldemar Gomes Pinto',
        addressNumber: '1407',
        district: 'Ponte Nova',
        zipCode: '37640000',
        phone: '(35) 3100-0300',
        websiteUrl: 'https://www.hotelvillalobos.com.br/',
        amenities: ['Hotel', 'Spa', 'Restaurante'],
        geo: {
          lat: -22.8548355,
          lng: -46.3184553,
          formattedAddress: 'Avenida Delegado Waldemar Gomes Pinto 1407, Ponte Nova, Extrema - MG, 37640-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.hotelvillalobos.com.br/',
        sortOrder: 10,
      },
      {
        name: 'Pousada Spa Saúde Melhor',
        slug: 'pousada-spa-saude-melhor',
        type: 'POUSADA',
        address: 'Rua das Acácias',
        addressNumber: '510',
        district: 'Vila Rica',
        zipCode: '37640000',
        websiteUrl: 'https://extrematur.com.br/onde-ficar/pousada/pousada-spa-saude-melhor',
        amenities: ['Pousada', 'Spa', 'Natureza'],
        geo: {
          lat: -22.8548355,
          lng: -46.3184553,
          formattedAddress: 'Rua das Acácias 510, Vila Rica, Extrema - MG, 37640-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://extrematur.com.br/onde-ficar/pousada/pousada-spa-saude-melhor',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Parque Ecológico Pico dos Cabritos',
        category: 'ATRATIVO',
        address: 'Parque Ecológico Pico dos Cabritos',
        addressNumber: '777',
        district: 'Extrema',
        zipCode: '37640000',
        featured: true,
        geo: {
          lat: -22.8594339,
          lng: -46.2952742,
          formattedAddress: 'Parque Ecológico Pico dos Cabritos, Extrema - MG, Brasil',
        },
        sourceUrl: 'https://extrematur.com.br/',
        sortOrder: 10,
      },
      {
        title: 'Serra do Lopo',
        category: 'PASSEIO',
        address: 'Serra do Lopo',
        addressNumber: 's/n',
        district: 'Extrema',
        zipCode: '37640000',
        featured: true,
        geo: {
          lat: -22.8548355,
          lng: -46.3184553,
          formattedAddress: 'Serra do Lopo, Extrema - MG, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://extrematur.com.br/',
        sortOrder: 20,
      },
      {
        title: 'Parque Municipal Cachoeira do Jaguari',
        category: 'ATRATIVO',
        address: 'Cachoeira do Jaguari',
        addressNumber: 's/n',
        district: 'Extrema',
        zipCode: '37640000',
        geo: {
          lat: -22.8548355,
          lng: -46.3184553,
          formattedAddress: 'Cachoeira do Jaguari, Extrema - MG, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://extrematur.com.br/',
        sortOrder: 30,
      },
      {
        title: 'Empyreo Destilaria',
        category: 'PASSEIO',
        address: 'Extrema',
        addressNumber: 's/n',
        district: 'Extrema',
        zipCode: '37640000',
        geo: {
          lat: -22.8548355,
          lng: -46.3184553,
          formattedAddress: 'Extrema - MG, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://extrematur.com.br/',
        sortOrder: 40,
      },
      {
        title: 'Restaurante Villa Ramos',
        category: 'RESTAURANTE_VISITAR',
        address: 'Extrema',
        addressNumber: 's/n',
        district: 'Extrema',
        zipCode: '37640000',
        geo: {
          lat: -22.8548355,
          lng: -46.3184553,
          formattedAddress: 'Extrema - MG, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://extrematur.com.br/',
        sortOrder: 50,
      },
    ],
  },
  {
    source: 'Visconde de Maua: pousadas, restaurantes, cachoeiras e geocoding regional validado',
    destination: {
      name: 'Visconde de Mauá',
      slug: 'visconde-de-maua',
      city: 'Visconde de Mauá',
      state: 'RJ',
      description:
        'Região de montanha entre Rio, Minas e São Paulo com pousadas, vilas gastronômicas, cachoeiras, Maromba, Maringá e natureza preservada.',
      heroTitle: 'Visconde de Mauá para desacelerar',
      heroSubtitle: 'Chalés, pousadas, cachoeiras e restaurantes de montanha no mesmo roteiro.',
      lat: -22.3311749,
      lng: -44.5326347,
      sortOrder: 80,
    },
    hospitality: [
      {
        name: 'Pousada Tijupá',
        slug: 'pousada-tijupa',
        type: 'POUSADA',
        address: 'Visconde de Mauá',
        addressNumber: 's/n',
        district: 'Visconde de Mauá',
        zipCode: '27553970',
        websiteUrl: 'https://www.tijupa.com.br/',
        amenities: ['Pousada', 'Natureza', 'Montanha'],
        geo: {
          lat: -22.3311749,
          lng: -44.5326347,
          formattedAddress: 'Visconde de Mauá, Resende - RJ, 27553-970, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.tijupa.com.br/',
        sortOrder: 10,
      },
      {
        name: 'Pousada Casa Bonita',
        slug: 'pousada-casa-bonita-visconde',
        type: 'POUSADA',
        address: 'Alto da Maromba',
        addressNumber: 's/n',
        district: 'Maromba',
        zipCode: '27553970',
        websiteUrl: 'https://pousadacasabonita.com.br/',
        amenities: ['Pousada', 'Cachoeira', 'Gastronomia'],
        geo: {
          lat: -22.32449,
          lng: -44.5970335,
          formattedAddress: 'Maromba, Itatiaia - RJ, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://pousadacasabonita.com.br/',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Cachoeira do Escorrega',
        category: 'ATRATIVO',
        address: 'Cachoeira do Escorrega',
        addressNumber: 's/n',
        district: 'Maromba',
        zipCode: '27553970',
        featured: true,
        geo: {
          lat: -22.32449,
          lng: -44.5970335,
          formattedAddress: 'Maromba, Itatiaia - RJ, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://viscondedemaua.com.br/',
        sortOrder: 10,
      },
      {
        title: 'Poção da Maromba',
        category: 'ATRATIVO',
        address: 'Poção da Maromba',
        addressNumber: 's/n',
        district: 'Maromba',
        zipCode: '27553970',
        geo: {
          lat: -22.32449,
          lng: -44.5970335,
          formattedAddress: 'Maromba, Itatiaia - RJ, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://viscondedemaua.com.br/',
        sortOrder: 20,
      },
      {
        title: 'Cachoeira Santa Clara',
        category: 'ATRATIVO',
        address: 'Cachoeira Santa Clara',
        addressNumber: 's/n',
        district: 'Visconde de Mauá',
        zipCode: '27553970',
        geo: {
          lat: -22.3311749,
          lng: -44.5326347,
          formattedAddress: 'Visconde de Mauá, Resende - RJ, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://viscondedemaua.com.br/',
        sortOrder: 30,
      },
      {
        title: 'Gosto com Gosto Restaurante',
        category: 'RESTAURANTE_VISITAR',
        address: 'Avenida Presidente Wenceslau Brás',
        addressNumber: 's/n',
        district: 'Visconde de Mauá',
        zipCode: '27553970',
        websiteUrl: 'https://www.gostocomgosto.com.br/',
        featured: true,
        geo: {
          lat: -22.3318817,
          lng: -44.5403659,
          formattedAddress: 'Gosto com Gosto Restaurante, Visconde de Mauá, Resende - RJ, 27553-970, Brasil',
        },
        sourceUrl: 'https://www.gostocomgosto.com.br/',
        sortOrder: 40,
      },
      {
        title: 'Babel Restaurante',
        category: 'RESTAURANTE_VISITAR',
        address: 'Estrada Mauá-Campo Alegre',
        addressNumber: 'km 4',
        district: 'Visconde de Mauá',
        zipCode: '27553970',
        websiteUrl: 'https://www.babelrestaurante.com.br/',
        featured: true,
        geo: {
          lat: -22.3311749,
          lng: -44.5326347,
          formattedAddress: 'Estrada Mauá-Campo Alegre km 4, Visconde de Mauá - RJ/MG, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.babelrestaurante.com.br/',
        sortOrder: 50,
      },
    ],
  },
  {
    source: 'Bueno Brandao: cachoeiras, pousadas, turismo rural e geocoding validado',
    destination: {
      name: 'Bueno Brandão',
      slug: 'bueno-brandao',
      city: 'Bueno Brandão',
      state: 'MG',
      description:
        'Destino mineiro de montanha conhecido pelas cachoeiras, turismo rural, pousadas, trilhas, mirantes e experiências simples de interior.',
      heroTitle: 'Bueno Brandão entre cachoeiras e montanhas',
      heroSubtitle: 'Pousadas, cachoeiras e pontos locais para planejar o passeio com facilidade.',
      lat: -22.441421,
      lng: -46.3475825,
      sortOrder: 85,
    },
    hospitality: [
      {
        name: 'Pousada Som das Águas',
        slug: 'pousada-som-das-aguas',
        type: 'POUSADA',
        address: 'Rua Vereador Vicente Alves Coutinho',
        addressNumber: 's/n',
        district: 'Serrinha',
        zipCode: '37578000',
        amenities: ['Pousada', 'Camping', 'Natureza'],
        geo: {
          lat: -22.4886925,
          lng: -46.392267,
          formattedAddress:
            'Pousada e Camping Som das Águas, Rua Vereador Vicente Alves Coutinho, Serrinha, Bueno Brandão - MG, 37578-000, Brasil',
        },
        sourceUrl: 'https://www.buenobrandao.mg.gov.br/',
        sortOrder: 10,
      },
      {
        name: 'Pousada Recanto das Cachoeiras',
        slug: 'pousada-recanto-das-cachoeiras',
        type: 'POUSADA',
        address: 'Bueno Brandão',
        addressNumber: 's/n',
        district: 'Bueno Brandão',
        zipCode: '37578000',
        amenities: ['Pousada', 'Cachoeiras', 'Hospedagem'],
        geo: {
          lat: -22.441421,
          lng: -46.3475825,
          formattedAddress: 'Bueno Brandão - MG, 37578-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.buenobrandao.mg.gov.br/',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Cachoeira dos Luís',
        category: 'ATRATIVO',
        address: 'Cachoeira dos Luís',
        addressNumber: 's/n',
        district: 'Bueno Brandão',
        zipCode: '37578000',
        featured: true,
        geo: {
          lat: -22.539011,
          lng: -46.3162221,
          formattedAddress: 'Cachoeira dos Luís, Bueno Brandão - MG, Brasil',
        },
        sourceUrl: 'https://www.buenobrandao.mg.gov.br/',
        sortOrder: 10,
      },
      {
        title: 'Cachoeira do Machado II',
        category: 'ATRATIVO',
        address: 'Cachoeira do Machado',
        addressNumber: 's/n',
        district: 'Bueno Brandão',
        zipCode: '37578000',
        geo: {
          lat: -22.490178,
          lng: -46.4086372,
          formattedAddress: 'Cachoeira do Machado II, Bueno Brandão - MG, Brasil',
        },
        sourceUrl: 'https://www.buenobrandao.mg.gov.br/',
        sortOrder: 20,
      },
      {
        title: 'Cachoeira dos Félix',
        category: 'ATRATIVO',
        address: 'Cachoeira dos Félix',
        addressNumber: 's/n',
        district: 'Bueno Brandão',
        zipCode: '37578000',
        geo: {
          lat: -22.4875403,
          lng: -46.3924094,
          formattedAddress: 'Cachoeira dos Félix, Bueno Brandão - MG, Brasil',
        },
        sourceUrl: 'https://www.buenobrandao.mg.gov.br/',
        sortOrder: 30,
      },
      {
        title: 'Cachoeira Santa Rita',
        category: 'ATRATIVO',
        address: 'Cachoeira Santa Rita',
        addressNumber: 's/n',
        district: 'Bueno Brandão',
        zipCode: '37578000',
        geo: {
          lat: -22.53333,
          lng: -46.31667,
          formattedAddress: 'Cachoeira Santa Rita, Bueno Brandão - MG, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.buenobrandao.mg.gov.br/',
        sortOrder: 40,
      },
    ],
  },
  {
    source: 'Delfim Moreira: turismo rural, Serra da Mantiqueira, Pico dos Marins, hospedagens e geocoding regional',
    destination: {
      name: 'Delfim Moreira',
      slug: 'delfim-moreira',
      city: 'Delfim Moreira',
      state: 'MG',
      description:
        'Cidade mineira da Serra da Mantiqueira com clima de montanha, turismo rural, cachoeiras, pousadas e acesso regional ao Pico dos Marins.',
      heroTitle: 'Delfim Moreira para viver a Mantiqueira',
      heroSubtitle: 'Hospedagens, cachoeiras, trilhas e pontos de apoio para um roteiro tranquilo.',
      lat: -22.5086783,
      lng: -45.2792398,
      sortOrder: 90,
    },
    hospitality: [
      {
        name: 'Hotel Fazenda Boa Esperança',
        slug: 'hotel-fazenda-boa-esperanca',
        type: 'HOTEL',
        address: 'Delfim Moreira',
        addressNumber: 's/n',
        district: 'Zona Rural',
        zipCode: '37514000',
        amenities: ['Hotel fazenda', 'Turismo rural', 'Natureza'],
        geo: {
          lat: -22.579459,
          lng: -45.321249,
          formattedAddress: 'Hotel Fazenda Boa Esperança, Delfim Moreira - MG, Brasil',
        },
        sourceUrl: 'https://www.delfimmoreira.mg.gov.br/',
        sortOrder: 10,
      },
      {
        name: 'Pousada de Montanha Delfim Moreira',
        slug: 'pousada-de-montanha-delfim-moreira',
        type: 'POUSADA',
        address: 'Delfim Moreira',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '37514000',
        amenities: ['Pousada', 'Montanha', 'Hospedagem'],
        geo: {
          lat: -22.5086783,
          lng: -45.2792398,
          formattedAddress: 'Delfim Moreira - MG, 37514-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.delfimmoreira.mg.gov.br/',
        sortOrder: 20,
      },
    ],
    listings: [
      {
        title: 'Estação Ferroviária de Delfim Moreira',
        category: 'ATRATIVO',
        address: 'Delfim Moreira',
        addressNumber: 's/n',
        district: 'Centro',
        zipCode: '37514000',
        geo: {
          lat: -22.505567,
          lng: -45.27822,
          formattedAddress: 'Estação Ferroviária, Delfim Moreira - MG, Brasil',
        },
        sourceUrl: 'https://www.delfimmoreira.mg.gov.br/',
        sortOrder: 10,
      },
      {
        title: 'Cachoeira do Itagyba',
        category: 'ATRATIVO',
        address: 'Cachoeira do Itagyba',
        addressNumber: 's/n',
        district: 'Delfim Moreira',
        zipCode: '37514000',
        featured: true,
        geo: {
          lat: -22.5086783,
          lng: -45.2792398,
          formattedAddress: 'Delfim Moreira - MG, 37514-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.delfimmoreira.mg.gov.br/',
        sortOrder: 20,
      },
      {
        title: 'Cachoeira Ninho da Águia',
        category: 'ATRATIVO',
        address: 'Cachoeira Ninho da Águia',
        addressNumber: 's/n',
        district: 'Delfim Moreira',
        zipCode: '37514000',
        geo: {
          lat: -22.5086783,
          lng: -45.2792398,
          formattedAddress: 'Delfim Moreira - MG, 37514-000, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.delfimmoreira.mg.gov.br/',
        sortOrder: 30,
      },
      {
        title: 'Pico dos Marins',
        category: 'PASSEIO',
        address: 'Pico dos Marins',
        addressNumber: 's/n',
        district: 'Serra da Mantiqueira',
        zipCode: '37514000',
        featured: true,
        geo: {
          lat: -22.5086783,
          lng: -45.2792398,
          formattedAddress: 'Região do Pico dos Marins, Delfim Moreira - MG, Brasil',
          precision: 'city',
        },
        sourceUrl: 'https://www.delfimmoreira.mg.gov.br/',
        sortOrder: 40,
      },
    ],
  },
];
