export const inputAssistProps = {
  search: {
    type: 'search',
    autoComplete: 'on',
    autoCorrect: 'on',
    autoCapitalize: 'sentences',
    spellCheck: true,
    inputMode: 'search',
  },
  name: {
    type: 'text',
    autoComplete: 'name',
    autoCorrect: 'on',
    autoCapitalize: 'words',
    spellCheck: true,
  },
  email: {
    type: 'email',
    autoComplete: 'email',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
    inputMode: 'email',
  },
  username: {
    autoComplete: 'username',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
  },
  currentPassword: {
    autoComplete: 'current-password',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
  },
  newPassword: {
    autoComplete: 'new-password',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
  },
  phone: {
    type: 'tel',
    autoComplete: 'tel',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
    inputMode: 'tel',
  },
  phoneNational: {
    type: 'tel',
    autoComplete: 'tel-national',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
    inputMode: 'tel',
  },
  document: {
    type: 'text',
    autoComplete: 'off',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
    inputMode: 'numeric',
  },
  postalCode: {
    type: 'text',
    autoComplete: 'postal-code',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
    inputMode: 'numeric',
  },
  addressLine1: {
    type: 'text',
    autoComplete: 'address-line1',
    autoCorrect: 'on',
    autoCapitalize: 'words',
    spellCheck: true,
  },
  addressLine2: {
    type: 'text',
    autoComplete: 'address-line2',
    autoCorrect: 'on',
    autoCapitalize: 'words',
    spellCheck: true,
  },
  addressLine3: {
    type: 'text',
    autoComplete: 'address-line3',
    autoCorrect: 'on',
    autoCapitalize: 'words',
    spellCheck: true,
  },
  neighborhood: {
    type: 'text',
    autoComplete: 'address-level3',
    autoCorrect: 'on',
    autoCapitalize: 'words',
    spellCheck: true,
  },
  city: {
    type: 'text',
    autoComplete: 'address-level2',
    autoCorrect: 'on',
    autoCapitalize: 'words',
    spellCheck: true,
  },
  state: {
    type: 'text',
    autoComplete: 'address-level1',
    autoCorrect: 'off',
    autoCapitalize: 'characters',
    spellCheck: false,
  },
  otp: {
    autoComplete: 'one-time-code',
    autoCorrect: 'off',
    autoCapitalize: 'none',
    spellCheck: false,
    inputMode: 'numeric',
  },
} as const;

export const textareaAssistProps = {
  notes: {
    autoComplete: 'on',
    autoCorrect: 'on',
    autoCapitalize: 'sentences',
    spellCheck: true,
  },
  description: {
    autoComplete: 'on',
    autoCorrect: 'on',
    autoCapitalize: 'sentences',
    spellCheck: true,
  },
} as const;
